#ifndef MULTICOPTER_MPC_INTERNAL_CONFIG_H_
#define MULTICOPTER_MPC_INTERNAL_CONFIG_H_

#define MULTICOPTER_MPC_ROOT_DIR "${MULTICOPTER_MPC_ROOT_DIR}"
#define MULTICOPTER_MPC_MULTIROTOR_DIR "${MULTICOPTER_MPC_MULTIROTOR_DIR}"
#define MULTICOPTER_MPC_MISSION_DIR "${MULTICOPTER_MPC_MISSION_DIR}"

#endif // MULTICOPTER_MPC_INTERNAL_CONFIG_H_
