multirotor:
    cf: 8.54858e-06
    cm: 1.3677728e-7 # (from Gazebo plugin: 1.6e-2*cf)
    max_thrust: 10.3437818 # (1100 rad/s)
    min_thrust: 0.0 # (0 rad/s)
    base_link_name: "base_link"
    $rotors:
        -   x:  0.1862
            y: -0.1075
            z: -1.0

        -   x: 0.1862
            y: 0.1075
            z: 1.0

        -   x: 0.0
            y: 0.215
            z: -1.0

        -   x: -0.1862
            y: 0.1075
            z: 1.0
        
        -   x: -0.1862
            y: -0.1075
            z: -1.0

        -   x: 0.0
            y: -0.215
            z: 1.0
