platform:
    cf: 8.54858e-06
    cm: 1.3677728e-7 # (from Gazebo plugin: 1.6e-2*cf)
    max_thrust: 10.3437818 # (1100 rad/s)
    min_thrust: 0.0 # (0 rad/s)
    base_link_name: "base_link"
    n_rotors: 6
    $rotors:
        - translation: [0.1862, -0.1075, 0.0]
          orientation: [1, 0, 0, 0]
          spin_direction: [1]

        - translation: [0.1862, -0.1075, 0.0]
          orientation: [1, 0, 0, 0]
          spin_direction: [1]
        
        - translation: [0.1862, -0.1075, 0.0]
          orientation: [1, 0, 0, 0]
          spin_direction: [1]

        - translation: [0.1862, -0.1075, 0.0]
          orientation: [1, 0, 0, 0]
          spin_direction: [1]
        
        - translation: [0.1862, -0.1075, 0.0]
          orientation: [1, 0, 0, 0]
          spin_direction: [1]
        
        - translation: [0.1862, -0.1075, 1.0]
          orientation: [1, 0, 0, 0]
          spin_direction: [1]
