trajectory:
  robot:
    name: "hexarotor_370_flying_arm_3"
    urdf: "/home/pepms/robotics/libraries/example-robot-data/robots/hexarotor_370_description/urdf/hexarotor_370_flying_arm_3.urdf"
    follow: "/home/pepms/robotics/libraries/multicopter-mpc/config/multicopter/hexacopter370.yaml"

  initial_state: [-5, 0, 1.5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

  stages:
    - name: "approach"
      duration: 1510 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights:
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1000, 1000, 1000]

        - name: "state_limits"
          type: "CostModelState"
          weight: 10
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1]
          u_bound: [0, 0, 0, 0, 0, 0, 1.9, 1.9, 1.9, 0, 0, 0, 0, 0, 0, 3, 3, 3]
          l_bound:
            [0, 0, 0, 0, 0, 0, -1.9, -1.9, -1.9, 0, 0, 0, 0, 0, 0, -3, -3, -3]

        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 10, 10, 10]

    - name: "pre_grasp"
      duration: 0 #ms
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights:
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1000, 1000, 1000]

        - name: "state_limits"
          type: "CostModelState"
          weight: 10
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1]
          u_bound: [0, 0, 0, 0, 0, 0, 1.9, 1.9, 1.9, 0, 0, 0, 0, 0, 0, 3, 3, 3]
          l_bound:
            [0, 0, 0, 0, 0, 0, -1.9, -1.9, -1.9, 0, 0, 0, 0, 0, 0, -3, -3, -3]

        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 10, 10, 10]

        - name: "translation_ee"
          type: "CostModelFrameTranslation"
          weight: 1e4
          link_name: "arm_ee"
          position: [0, 0, 0]

        - name: "motion_ee"
          type: "CostModelFrameVelocity"
          weight: 1e3
          link_name: "arm_ee"
          linear: [0, 0, 0]
          angular: [0, 0, 0]
    - name: "grasp"
      duration: 160 #ms
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-3
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights:
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1000, 1000, 1000]
        - name: "state_limits"
          type: "CostModelState"
          weight: 10
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1]
          u_bound: [0, 0, 0, 0, 0, 0, 1.9, 1.9, 1.9, 0, 0, 0, 0, 0, 0, 3, 3, 3]
          l_bound:
            [0, 0, 0, 0, 0, 0, -1.9, -1.9, -1.9, 0, 0, 0, 0, 0, 0, -3, -3, -3]
        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 10, 10, 10]
        - name: "translation_ee"
          type: "CostModelFrameTranslation"
          weight: 1000
          link_name: "arm_ee"
          position: [0, 0, 0]
        - name: "motion_ee"
          type: "CostModelFrameVelocity"
          weight: 1000
          link_name: "arm_ee"
          linear: [0, 0, 0]
          angular: [0, 0, 0]
        - name: "friction_cone"
          type: "CostModelContactFrictionCone"
          weight: 10
          n_surf: [0, 0, 1]
          mu: 0.7
          link_name: "arm_ee"
      contacts:
        - name: "end_effector"
          type: "ContactModel3D"
          link_name: "arm_ee"
          position: [0, 0, 0]
          gains: [0, 0]
    - name: "move_away"
      duration: 1510 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights:
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1000, 1000, 1000]
        - name: "state_limits"
          type: "CostModelState"
          weight: 10
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1]
          u_bound: [0, 0, 0, 0, 0, 0, 1.9, 1.9, 1.9, 0, 0, 0, 0, 0, 0, 3, 3, 3]
          l_bound:
            [0, 0, 0, 0, 0, 0, -1.9, -1.9, -1.9, 0, 0, 0, 0, 0, 0, -3, -3, -3]
        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 10, 10, 10]
    - name: "hover"
      duration: 0 #ms
      costs:
        - name: "state_arm"
          type: "CostModelState"
          weight: 2000
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1]
        - name: "placement_base_link"
          type: "CostModelFramePlacement"
          weight: 2000
          link_name: "base_link"
          position: [5, 0, 1.5]
          orientation: [0, 0, 0, 1] # x,y,z,w
        - name: "motion_base_link"
          type: "CostModelFrameVelocity"
          weight: 2000
          link_name: "base_link"
          linear: [0, 0, 0]
          angular: [0, 0, 0]
