trajectory:
  robot:
    name: "iris"
    urdf: "/home/pepms/robotics/libraries/example-robot-data/robots/iris_description/robots/iris.urdf"
    follow: "/home/pepms/robotics/libraries/multicopter-mpc/config/multicopter/iris.yaml"
  
  stages:
    - name: "nav_wp1"
      duration: 2000 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

    - name: "wp1"
      duration: 0 #ms
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

        - name: "placement_base_link"
          type: "CostModelFramePlacement"
          weight: 1000
          link_name: "iris__base_link"
          position: [0, 0, 2.5]
          orientation: [0, 0, 0, 1] # x,y,z,w

        - name: "motion_base_link"
          type: "CostModelFrameVelocity"
          weight: 1000
          link_name: "iris__base_link"
          linear: [0, 0, 0]
          angular: [0, 0, 0]

    - name: "nav_wp2"
      duration: 1400 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

    - name: "wp2"
      duration: 0 #ms
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

        - name: "placement_base_link"
          type: "CostModelFramePlacement"
          weight: 1000
          link_name: "iris__base_link"
          position: [6.0, 0, 2.0]
          orientation: [1, 0, 0, 1] # x,y,z,w

        - name: "motion_base_link"
          type: "CostModelFrameVelocity"
          weight: 1000
          link_name: "iris__base_link"
          linear: [5.0, 0, 0]
          angular: [0, 0, 0]
    
    - name: "nav_wp3"
      duration: 1500 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

    - name: "wp3"
      duration: 0 #ms
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "control_reg"
          type: "CostModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1]

        - name: "placement_base_link"
          type: "CostModelFramePlacement"
          weight: 2000
          link_name: "iris__base_link"
          position: [11.0, 0, 2.0]
          orientation: [0, 0, 0, 1] # x,y,z,w

        - name: "motion_base_link"
          type: "CostModelFrameVelocity"
          weight: 1000
          link_name: "iris__base_link"
          linear: [0, 0, 0]
          angular: [0, 0, 0]
