mission:
  $initial_state:
    - pos: [0.0, 2.0, 2.5]
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      vel_lin: [-3.0, 0.0, 0.0]
      vel_rot: [0.0, 0.0, 0.0]

  $waypoints:    
    - pos: [0.0, 0.0, 2.5]
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      vel_lin: [1.0, 2.0, 3.0]
      vel_rot: [-3.0, -2.0, -1.0]
      time: 2.0