multirotor:
    cf: 5.5e-5
    cm: 6.0e-6
    max_thrust: 10
    min_thrust: 0.1
    $rotors:
        -   x: 0.1525
            y: 0.0
            z: -1.0

        -   x: 0.0
            y: 0.1525
            z: 1.0

        -   x: -0.1525
            y: 0.0
            z: -1.0

        -   x: 0.0
            y: -0.1525
            z: 1.0

