multirotor:
    cf: 8.54858e-06
    cm: 5.129148e-07
    max_thrust: 10.3437818
    min_thrust: 0.0854858
    $rotors:
        -   x:  0.13
            y: -0.22
            z: -1.0

        -   x: 0.13
            y: 0.22
            z: 1.0

        -   x: -0.13
            y: 0.2
            z: -1.0

        -   x: -0.13
            y: -0.2
            z: 1.0

