mission:
  $initial_state:
    - pos: [0.0, 0.0, 0.0]
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      vel_lin: [0.0, 0.0, 0.0]
      vel_rot: [0.0, 0.0, 0.0]

  $waypoints:    
    - pos: [0.0, 0.0, 1.0]
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      knots: 100

    - pos: [1.0, 0.0, 1.0]
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      vel_lin: [0.0, 0.0, 0.0]
      vel_rot: [0.0, 0.0, 0.0]
      knots: 100