mpc_controller:
  robot:
    name: "hexacopter370"
    urdf: "/home/pepms/robotics/libraries/example-robot-data/robots/hexacopter370_description/urdf/hexacopter370.urdf"
    follow: "/home/pepms/robotics/libraries/multicopter-mpc/config/multicopter/hexacopter370.yaml"
  integration_method: "IntegratedActionModelEuler"
  knots: 51
  solver: "SolverSbFDDP"
  iters: 2
  dt: 20

  carrot_weight: 1000

  rail_weight: 1000
  rail_activation_weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  rail_control_weight: 1e-1