mpc_controller:
  robot:
    name: "iris"
    urdf: "/home/pepms/robotics/libraries/example-robot-data/robots/iris_description/robots/iris.urdf"
    follow: "/home/pepms/robotics/libraries/multicopter-mpc/config/multicopter/iris.yaml"
  integration_method: "IntegratedActionModelEuler"
  knots: 51
  solver: "SolverSbFDDP"
  iters: 5
  dt: 20
  carrot_weight: 1000