trajectory_generator:
  solver: "BoxFDDP"
  integrator: "Euler"
  yaml_path: "/usr/local/share/multicopter_mpc/ocp/trajectory-generator.yaml"
  initial_guess: "SE3"
ocp:
  dt: 4e-3
  n_knots: 100  
  cost_running_state_weight: 1e-5
  cost_running_control_weight: 8e-2
  cost_running_pos_weight: 12000.0
  cost_running_vel_weight: 12000.0
  cost_terminal_pos_weight: 50.0
  cost_terminal_vel_weight: 50.0
  $state_weights:
    - position: [1.0, 1.0, 1.0]
      orientation: [1.0, 1.0, 1.0]
      velocity_lin: [1.0, 1.0, 1.0]
      velocity_ang: [1.0, 1.0, 1.0]