ocp:
  cost_state_weight: 1
  cost_control_weight: 0.05
  $state_weights:
    - position: [10.0, 10.0, 10.0]
      orientation: [3.0, 3.0, 3.0]
      velocity_lin: [0.05, 0.05, 0.05]
      velocity_ang: [0.1, 0.1, 0.1]
