ocp:
  cost_state_weight: 1
  cost_control_weight: 0.05
  $state_weights:
    - position: [20.0, 20.0, 20.0]
      orientation: [2, 2, 2]
      velocity_lin: [0.01, 0.01, 0.01]
      velocity_ang: [0.01, 0.01, 0.01]
