trajectory_generator:
  solver: "BoxFDDP"
  integrator: "Euler"
  yaml_path: "/usr/local/share/multicopter_mpc/ocp/trajectory-generator.yaml"
  initial_guess: "SE3"
ocp:
  dt: 4e-3
  n_knots: 101
  cost_state_weight: 1
  cost_control_weight: 1
  $state_weights:
    - position: [1000.0, 1000.0, 1000.0]
      orientation: [1000.0, 1000.0, 1000.0]
      velocity_lin: [1, 1, 1]
      velocity_ang: [1, 1, 1]
