ocp:
  cost_state_weight: 1
  cost_control_weight: 1
  $state_weights:
    - position: [1000.0, 1000.0, 1000.0]
      orientation: [1000.0, 1000.0, 1000.0]
      velocity_lin: [1, 1, 1]
      velocity_ang: [1, 1, 1]
