ocp:
  cost_state_weight: 1
  cost_control_weight: 1
  $state_weights:
    - position: [100.0, 100.0, 100.0]
      orientation: [100.0, 100.0, 100.0]
      velocity_lin: [0.1, 0.1, 0.1]
      velocity_ang: [0.5, 0.5, 0.5]
