mission:
  $initial_state:
    - pos: [0.0, 0.0, 0.0] 
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      vel_lin: [0.0, 0.0, 0.0]
      vel_rot: [0.0, 0.0, 0.0]

  $waypoints:
    - pos: [0.0, 0.0, 1.0]
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      vel_lin: [0.0, 0.0, 0.0]
      vel_rot: [0.0, 0.0, 0.0]
      time: 1.0

    - pos: [0.0, 0.0, 6.0]
      quat: [1.0, 0.0, 0.0, 0.0] # x, y, z, w
      vel_lin: [0.0, 4.0, 0.0]
      vel_rot: [2.0, 0.0, 0.0]
      time: 1.5

    - pos: [0.0, 0.0, 2.0]
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      vel_lin: [0.0, 0.0, 0.0]
      vel_rot: [0.0, 0.0, 0.0]
      time: 3.0