multirotor:
    cf: 6.6e-5
    cm: 1.0e-6 
    max_thrust: 5
    min_thrust: 0.1
    base_link_name: "base_link"
    $rotors:
        -   x: 0.1525
            y: 0.0
            z: -1.0

        -   x: 0.0
            y: 0.1525
            z: 1.0

        -   x: -0.1525
            y: 0.0
            z: -1.0

        -   x: 0.0
            y: -0.1525
            z: 1.0
