multirotor:
    cf: 8.54858e-06
    cm: 1.3677728e-7 # (from Gazebo plugin: 1.6e-2*cf)
    max_thrust: 6.0031890135 # (838 rad/s)
    min_thrust: 0.0 # (0 rad/s)
    base_link_name: "iris__base_link"
    $rotors:
        -   x:  0.13
            y: -0.22
            z: -1.0

        -   x: -0.13
            y: 0.2
            z: -1.0

        -   x: 0.13
            y: 0.22
            z: 1.0

        -   x: -0.13
            y: -0.2
            z: 1.0
