get_filename_component(SELF_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
include(${SELF_DIR}/${CMAKE_BUILD_TYPE}/eagle_mpc.cmake)
set(eagle_mpc_INCLUDE_DIRS "/usr/local/include")
set(EAGLE_MPC_INCLUDE_DIRS "/usr/local/include")
set(eagle_mpc_LIBRARIES "/usr/local/lib/libeagle_mpc.so")
set(EAGLE_MPC_LIBRARIES "/usr/local/lib/libeagle_mpc.so")